### ISSUE TITLE
报错：无法估算需要的gas

### ISSUE THREAD

**Issue by nifflin** [nkbai/go-callcontract-example#2]
具体报错如下：
Failed to deploy new token contract: failed to estimate gas needed: gas required exceeds allowance or always failing transaction

钱包里有0.15ETH，应该足够部署了。

**Comment by nkbai** [comment]
我一直都是在测试网络上工作,没有有eth的账号

**Comment by nkbai** [comment]
这个错误是因为你的这个 contract 执行肯定会出错。或者这个合约调用需要的 gas 超过本地限制。一个以太坊节点会统一指定一个每次执行合约最多可以消耗多少 gas 的，这个我搭建私链的时候都是写在创世区块中的。
